---
- name: This playbook is to install tree package
  hosts: all
  become: true
  tasks:
  - name: To install httpd package
    yum:
      name: httpd
      state: installed
  - name: To start httpd service
    service: 
      name: httpd
      state: started

