---
- name: This playbook is to setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java on redhat
    yum: 
     name: java
     state: installed
    when: ansible_os_family == "RedHat"

  - name: install default-jdk on Debian
    apt: 
     name: default-jdk
     state: present
    when: ansible_os_family == "Debian"
   
  - name: Download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
      dest: /opt
  
  - name: extracting tomcat
    unarchive: 
      src: /opt/apache-tomcat-8.5.83.tar.gz
      dest: /opt
      remote_src: yes

  - name: Add executable permissions
    file:
      path: /opt/apache-tomcat-8.5.83/bin/startup.sh
      mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.83/bin

