---
- name: This playbook is to uninstall httpd package
  hosts: all
  become: true
  tasks:
  - name: To stop httpd service
    service: 
      name: httpd
      state: stopped
  - name: To uninstall httpd package
    yum:
      name: httpd
      state: removed
